version: '3.7'
services:
  api:
    container_name: api
    build: .
    ports: 
      - "3333:3333"
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/db:/data/db